package com.gps.manager.entity;

import java.io.Serializable;
import java.util.Date;

import org.apache.poi.hssf.usermodel.HSSFSheet;

public class Attach implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5312646609045798418L;


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach.attach_id
     *
     * @mbggenerated
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attach.relation_id
     *
     * @mbggenerated
     */
    private Integer relationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach.attach_id
     *
     * @return the value of attach.attach_id
     *
     * @mbggenerated
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach.attach_id
     *
     * @param attachId the value for attach.attach_id
     *
     * @mbggenerated
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach.file_name
     *
     * @return the value of attach.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach.file_name
     *
     * @param fileName the value for attach.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach.file_path
     *
     * @return the value of attach.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach.file_path
     *
     * @param filePath the value for attach.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach.create_time
     *
     * @return the value of attach.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach.create_time
     *
     * @param createTime the value for attach.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attach.relation_id
     *
     * @return the value of attach.relation_id
     *
     * @mbggenerated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attach.relation_id
     *
     * @param relationId the value for attach.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }
}