package com.gps.manager.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GpsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gps
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gps
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gps
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public GpsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gps
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDidIsNull() {
            addCriterion("did is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("did is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("did =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("did <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("did >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("did >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("did <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("did <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("did in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("did not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("did between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("did not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDevIdIsNull() {
            addCriterion("dev_id is null");
            return (Criteria) this;
        }

        public Criteria andDevIdIsNotNull() {
            addCriterion("dev_id is not null");
            return (Criteria) this;
        }

        public Criteria andDevIdEqualTo(Long value) {
            addCriterion("dev_id =", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdNotEqualTo(Long value) {
            addCriterion("dev_id <>", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdGreaterThan(Long value) {
            addCriterion("dev_id >", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dev_id >=", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdLessThan(Long value) {
            addCriterion("dev_id <", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdLessThanOrEqualTo(Long value) {
            addCriterion("dev_id <=", value, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdIn(List<Long> values) {
            addCriterion("dev_id in", values, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdNotIn(List<Long> values) {
            addCriterion("dev_id not in", values, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdBetween(Long value1, Long value2) {
            addCriterion("dev_id between", value1, value2, "devId");
            return (Criteria) this;
        }

        public Criteria andDevIdNotBetween(Long value1, Long value2) {
            addCriterion("dev_id not between", value1, value2, "devId");
            return (Criteria) this;
        }

        public Criteria andDevSnoIsNull() {
            addCriterion("dev_sno is null");
            return (Criteria) this;
        }

        public Criteria andDevSnoIsNotNull() {
            addCriterion("dev_sno is not null");
            return (Criteria) this;
        }

        public Criteria andDevSnoEqualTo(String value) {
            addCriterion("dev_sno =", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoNotEqualTo(String value) {
            addCriterion("dev_sno <>", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoGreaterThan(String value) {
            addCriterion("dev_sno >", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoGreaterThanOrEqualTo(String value) {
            addCriterion("dev_sno >=", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoLessThan(String value) {
            addCriterion("dev_sno <", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoLessThanOrEqualTo(String value) {
            addCriterion("dev_sno <=", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoLike(String value) {
            addCriterion("dev_sno like", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoNotLike(String value) {
            addCriterion("dev_sno not like", value, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoIn(List<String> values) {
            addCriterion("dev_sno in", values, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoNotIn(List<String> values) {
            addCriterion("dev_sno not in", values, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoBetween(String value1, String value2) {
            addCriterion("dev_sno between", value1, value2, "devSno");
            return (Criteria) this;
        }

        public Criteria andDevSnoNotBetween(String value1, String value2) {
            addCriterion("dev_sno not between", value1, value2, "devSno");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdIsNull() {
            addCriterion("ext_firm_id is null");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdIsNotNull() {
            addCriterion("ext_firm_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdEqualTo(Integer value) {
            addCriterion("ext_firm_id =", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdNotEqualTo(Integer value) {
            addCriterion("ext_firm_id <>", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdGreaterThan(Integer value) {
            addCriterion("ext_firm_id >", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_firm_id >=", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdLessThan(Integer value) {
            addCriterion("ext_firm_id <", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_firm_id <=", value, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdIn(List<Integer> values) {
            addCriterion("ext_firm_id in", values, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdNotIn(List<Integer> values) {
            addCriterion("ext_firm_id not in", values, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_firm_id between", value1, value2, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtFirmIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_firm_id not between", value1, value2, "extFirmId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdIsNull() {
            addCriterion("ext_mode_id is null");
            return (Criteria) this;
        }

        public Criteria andExtModeIdIsNotNull() {
            addCriterion("ext_mode_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtModeIdEqualTo(Integer value) {
            addCriterion("ext_mode_id =", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdNotEqualTo(Integer value) {
            addCriterion("ext_mode_id <>", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdGreaterThan(Integer value) {
            addCriterion("ext_mode_id >", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_mode_id >=", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdLessThan(Integer value) {
            addCriterion("ext_mode_id <", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_mode_id <=", value, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdIn(List<Integer> values) {
            addCriterion("ext_mode_id in", values, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdNotIn(List<Integer> values) {
            addCriterion("ext_mode_id not in", values, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_mode_id between", value1, value2, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtModeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_mode_id not between", value1, value2, "extModeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdIsNull() {
            addCriterion("ext_type_id is null");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdIsNotNull() {
            addCriterion("ext_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdEqualTo(Integer value) {
            addCriterion("ext_type_id =", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdNotEqualTo(Integer value) {
            addCriterion("ext_type_id <>", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdGreaterThan(Integer value) {
            addCriterion("ext_type_id >", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ext_type_id >=", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdLessThan(Integer value) {
            addCriterion("ext_type_id <", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("ext_type_id <=", value, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdIn(List<Integer> values) {
            addCriterion("ext_type_id in", values, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdNotIn(List<Integer> values) {
            addCriterion("ext_type_id not in", values, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("ext_type_id between", value1, value2, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andExtTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ext_type_id not between", value1, value2, "extTypeId");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("proj_id is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("proj_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Integer value) {
            addCriterion("proj_id <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Integer value) {
            addCriterion("proj_id >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("proj_id >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Integer value) {
            addCriterion("proj_id <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Integer value) {
            addCriterion("proj_id <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Integer> values) {
            addCriterion("proj_id in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Integer> values) {
            addCriterion("proj_id not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Integer value1, Integer value2) {
            addCriterion("proj_id between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("proj_id not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProdNoIsNull() {
            addCriterion("prod_no is null");
            return (Criteria) this;
        }

        public Criteria andProdNoIsNotNull() {
            addCriterion("prod_no is not null");
            return (Criteria) this;
        }

        public Criteria andProdNoEqualTo(Integer value) {
            addCriterion("prod_no =", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoNotEqualTo(Integer value) {
            addCriterion("prod_no <>", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoGreaterThan(Integer value) {
            addCriterion("prod_no >", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("prod_no >=", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoLessThan(Integer value) {
            addCriterion("prod_no <", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoLessThanOrEqualTo(Integer value) {
            addCriterion("prod_no <=", value, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoIn(List<Integer> values) {
            addCriterion("prod_no in", values, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoNotIn(List<Integer> values) {
            addCriterion("prod_no not in", values, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoBetween(Integer value1, Integer value2) {
            addCriterion("prod_no between", value1, value2, "prodNo");
            return (Criteria) this;
        }

        public Criteria andProdNoNotBetween(Integer value1, Integer value2) {
            addCriterion("prod_no not between", value1, value2, "prodNo");
            return (Criteria) this;
        }

        public Criteria andDevTsIsNull() {
            addCriterion("dev_ts is null");
            return (Criteria) this;
        }

        public Criteria andDevTsIsNotNull() {
            addCriterion("dev_ts is not null");
            return (Criteria) this;
        }

        public Criteria andDevTsEqualTo(Long value) {
            addCriterion("dev_ts =", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsNotEqualTo(Long value) {
            addCriterion("dev_ts <>", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsGreaterThan(Long value) {
            addCriterion("dev_ts >", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsGreaterThanOrEqualTo(Long value) {
            addCriterion("dev_ts >=", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsLessThan(Long value) {
            addCriterion("dev_ts <", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsLessThanOrEqualTo(Long value) {
            addCriterion("dev_ts <=", value, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsIn(List<Long> values) {
            addCriterion("dev_ts in", values, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsNotIn(List<Long> values) {
            addCriterion("dev_ts not in", values, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsBetween(Long value1, Long value2) {
            addCriterion("dev_ts between", value1, value2, "devTs");
            return (Criteria) this;
        }

        public Criteria andDevTsNotBetween(Long value1, Long value2) {
            addCriterion("dev_ts not between", value1, value2, "devTs");
            return (Criteria) this;
        }

        public Criteria andBasAccIsNull() {
            addCriterion("bas_acc is null");
            return (Criteria) this;
        }

        public Criteria andBasAccIsNotNull() {
            addCriterion("bas_acc is not null");
            return (Criteria) this;
        }

        public Criteria andBasAccEqualTo(Integer value) {
            addCriterion("bas_acc =", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccNotEqualTo(Integer value) {
            addCriterion("bas_acc <>", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccGreaterThan(Integer value) {
            addCriterion("bas_acc >", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccGreaterThanOrEqualTo(Integer value) {
            addCriterion("bas_acc >=", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccLessThan(Integer value) {
            addCriterion("bas_acc <", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccLessThanOrEqualTo(Integer value) {
            addCriterion("bas_acc <=", value, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccIn(List<Integer> values) {
            addCriterion("bas_acc in", values, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccNotIn(List<Integer> values) {
            addCriterion("bas_acc not in", values, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccBetween(Integer value1, Integer value2) {
            addCriterion("bas_acc between", value1, value2, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasAccNotBetween(Integer value1, Integer value2) {
            addCriterion("bas_acc not between", value1, value2, "basAcc");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaIsNull() {
            addCriterion("bas_defe_sta is null");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaIsNotNull() {
            addCriterion("bas_defe_sta is not null");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaEqualTo(Integer value) {
            addCriterion("bas_defe_sta =", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaNotEqualTo(Integer value) {
            addCriterion("bas_defe_sta <>", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaGreaterThan(Integer value) {
            addCriterion("bas_defe_sta >", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaGreaterThanOrEqualTo(Integer value) {
            addCriterion("bas_defe_sta >=", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaLessThan(Integer value) {
            addCriterion("bas_defe_sta <", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaLessThanOrEqualTo(Integer value) {
            addCriterion("bas_defe_sta <=", value, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaIn(List<Integer> values) {
            addCriterion("bas_defe_sta in", values, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaNotIn(List<Integer> values) {
            addCriterion("bas_defe_sta not in", values, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaBetween(Integer value1, Integer value2) {
            addCriterion("bas_defe_sta between", value1, value2, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasDefeStaNotBetween(Integer value1, Integer value2) {
            addCriterion("bas_defe_sta not between", value1, value2, "basDefeSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaIsNull() {
            addCriterion("bas_ride_sta is null");
            return (Criteria) this;
        }

        public Criteria andBasRideStaIsNotNull() {
            addCriterion("bas_ride_sta is not null");
            return (Criteria) this;
        }

        public Criteria andBasRideStaEqualTo(Integer value) {
            addCriterion("bas_ride_sta =", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaNotEqualTo(Integer value) {
            addCriterion("bas_ride_sta <>", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaGreaterThan(Integer value) {
            addCriterion("bas_ride_sta >", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaGreaterThanOrEqualTo(Integer value) {
            addCriterion("bas_ride_sta >=", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaLessThan(Integer value) {
            addCriterion("bas_ride_sta <", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaLessThanOrEqualTo(Integer value) {
            addCriterion("bas_ride_sta <=", value, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaIn(List<Integer> values) {
            addCriterion("bas_ride_sta in", values, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaNotIn(List<Integer> values) {
            addCriterion("bas_ride_sta not in", values, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaBetween(Integer value1, Integer value2) {
            addCriterion("bas_ride_sta between", value1, value2, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasRideStaNotBetween(Integer value1, Integer value2) {
            addCriterion("bas_ride_sta not between", value1, value2, "basRideSta");
            return (Criteria) this;
        }

        public Criteria andBasReasonIsNull() {
            addCriterion("bas_reason is null");
            return (Criteria) this;
        }

        public Criteria andBasReasonIsNotNull() {
            addCriterion("bas_reason is not null");
            return (Criteria) this;
        }

        public Criteria andBasReasonEqualTo(Integer value) {
            addCriterion("bas_reason =", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonNotEqualTo(Integer value) {
            addCriterion("bas_reason <>", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonGreaterThan(Integer value) {
            addCriterion("bas_reason >", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonGreaterThanOrEqualTo(Integer value) {
            addCriterion("bas_reason >=", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonLessThan(Integer value) {
            addCriterion("bas_reason <", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonLessThanOrEqualTo(Integer value) {
            addCriterion("bas_reason <=", value, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonIn(List<Integer> values) {
            addCriterion("bas_reason in", values, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonNotIn(List<Integer> values) {
            addCriterion("bas_reason not in", values, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonBetween(Integer value1, Integer value2) {
            addCriterion("bas_reason between", value1, value2, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasReasonNotBetween(Integer value1, Integer value2) {
            addCriterion("bas_reason not between", value1, value2, "basReason");
            return (Criteria) this;
        }

        public Criteria andBasSensorIsNull() {
            addCriterion("bas_sensor is null");
            return (Criteria) this;
        }

        public Criteria andBasSensorIsNotNull() {
            addCriterion("bas_sensor is not null");
            return (Criteria) this;
        }

        public Criteria andBasSensorEqualTo(Integer value) {
            addCriterion("bas_sensor =", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorNotEqualTo(Integer value) {
            addCriterion("bas_sensor <>", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorGreaterThan(Integer value) {
            addCriterion("bas_sensor >", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorGreaterThanOrEqualTo(Integer value) {
            addCriterion("bas_sensor >=", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorLessThan(Integer value) {
            addCriterion("bas_sensor <", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorLessThanOrEqualTo(Integer value) {
            addCriterion("bas_sensor <=", value, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorIn(List<Integer> values) {
            addCriterion("bas_sensor in", values, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorNotIn(List<Integer> values) {
            addCriterion("bas_sensor not in", values, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorBetween(Integer value1, Integer value2) {
            addCriterion("bas_sensor between", value1, value2, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasSensorNotBetween(Integer value1, Integer value2) {
            addCriterion("bas_sensor not between", value1, value2, "basSensor");
            return (Criteria) this;
        }

        public Criteria andBasFcodeIsNull() {
            addCriterion("bas_fcode is null");
            return (Criteria) this;
        }

        public Criteria andBasFcodeIsNotNull() {
            addCriterion("bas_fcode is not null");
            return (Criteria) this;
        }

        public Criteria andBasFcodeEqualTo(String value) {
            addCriterion("bas_fcode =", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeNotEqualTo(String value) {
            addCriterion("bas_fcode <>", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeGreaterThan(String value) {
            addCriterion("bas_fcode >", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeGreaterThanOrEqualTo(String value) {
            addCriterion("bas_fcode >=", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeLessThan(String value) {
            addCriterion("bas_fcode <", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeLessThanOrEqualTo(String value) {
            addCriterion("bas_fcode <=", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeLike(String value) {
            addCriterion("bas_fcode like", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeNotLike(String value) {
            addCriterion("bas_fcode not like", value, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeIn(List<String> values) {
            addCriterion("bas_fcode in", values, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeNotIn(List<String> values) {
            addCriterion("bas_fcode not in", values, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeBetween(String value1, String value2) {
            addCriterion("bas_fcode between", value1, value2, "basFcode");
            return (Criteria) this;
        }

        public Criteria andBasFcodeNotBetween(String value1, String value2) {
            addCriterion("bas_fcode not between", value1, value2, "basFcode");
            return (Criteria) this;
        }

        public Criteria andGpsLngIsNull() {
            addCriterion("gps_lng is null");
            return (Criteria) this;
        }

        public Criteria andGpsLngIsNotNull() {
            addCriterion("gps_lng is not null");
            return (Criteria) this;
        }

        public Criteria andGpsLngEqualTo(BigDecimal value) {
            addCriterion("gps_lng =", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotEqualTo(BigDecimal value) {
            addCriterion("gps_lng <>", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngGreaterThan(BigDecimal value) {
            addCriterion("gps_lng >", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("gps_lng >=", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngLessThan(BigDecimal value) {
            addCriterion("gps_lng <", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngLessThanOrEqualTo(BigDecimal value) {
            addCriterion("gps_lng <=", value, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngIn(List<BigDecimal> values) {
            addCriterion("gps_lng in", values, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotIn(List<BigDecimal> values) {
            addCriterion("gps_lng not in", values, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gps_lng between", value1, value2, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLngNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gps_lng not between", value1, value2, "gpsLng");
            return (Criteria) this;
        }

        public Criteria andGpsLatIsNull() {
            addCriterion("gps_lat is null");
            return (Criteria) this;
        }

        public Criteria andGpsLatIsNotNull() {
            addCriterion("gps_lat is not null");
            return (Criteria) this;
        }

        public Criteria andGpsLatEqualTo(BigDecimal value) {
            addCriterion("gps_lat =", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotEqualTo(BigDecimal value) {
            addCriterion("gps_lat <>", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatGreaterThan(BigDecimal value) {
            addCriterion("gps_lat >", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("gps_lat >=", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatLessThan(BigDecimal value) {
            addCriterion("gps_lat <", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("gps_lat <=", value, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatIn(List<BigDecimal> values) {
            addCriterion("gps_lat in", values, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotIn(List<BigDecimal> values) {
            addCriterion("gps_lat not in", values, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gps_lat between", value1, value2, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gps_lat not between", value1, value2, "gpsLat");
            return (Criteria) this;
        }

        public Criteria andGpsSpdIsNull() {
            addCriterion("gps_spd is null");
            return (Criteria) this;
        }

        public Criteria andGpsSpdIsNotNull() {
            addCriterion("gps_spd is not null");
            return (Criteria) this;
        }

        public Criteria andGpsSpdEqualTo(Integer value) {
            addCriterion("gps_spd =", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdNotEqualTo(Integer value) {
            addCriterion("gps_spd <>", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdGreaterThan(Integer value) {
            addCriterion("gps_spd >", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gps_spd >=", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdLessThan(Integer value) {
            addCriterion("gps_spd <", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdLessThanOrEqualTo(Integer value) {
            addCriterion("gps_spd <=", value, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdIn(List<Integer> values) {
            addCriterion("gps_spd in", values, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdNotIn(List<Integer> values) {
            addCriterion("gps_spd not in", values, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdBetween(Integer value1, Integer value2) {
            addCriterion("gps_spd between", value1, value2, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsSpdNotBetween(Integer value1, Integer value2) {
            addCriterion("gps_spd not between", value1, value2, "gpsSpd");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingIsNull() {
            addCriterion("gps_heading is null");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingIsNotNull() {
            addCriterion("gps_heading is not null");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingEqualTo(Integer value) {
            addCriterion("gps_heading =", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingNotEqualTo(Integer value) {
            addCriterion("gps_heading <>", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingGreaterThan(Integer value) {
            addCriterion("gps_heading >", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingGreaterThanOrEqualTo(Integer value) {
            addCriterion("gps_heading >=", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingLessThan(Integer value) {
            addCriterion("gps_heading <", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingLessThanOrEqualTo(Integer value) {
            addCriterion("gps_heading <=", value, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingIn(List<Integer> values) {
            addCriterion("gps_heading in", values, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingNotIn(List<Integer> values) {
            addCriterion("gps_heading not in", values, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingBetween(Integer value1, Integer value2) {
            addCriterion("gps_heading between", value1, value2, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsHeadingNotBetween(Integer value1, Integer value2) {
            addCriterion("gps_heading not between", value1, value2, "gpsHeading");
            return (Criteria) this;
        }

        public Criteria andGpsTsIsNull() {
            addCriterion("gps_ts is null");
            return (Criteria) this;
        }

        public Criteria andGpsTsIsNotNull() {
            addCriterion("gps_ts is not null");
            return (Criteria) this;
        }

        public Criteria andGpsTsEqualTo(Long value) {
            addCriterion("gps_ts =", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsNotEqualTo(Long value) {
            addCriterion("gps_ts <>", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsGreaterThan(Long value) {
            addCriterion("gps_ts >", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsGreaterThanOrEqualTo(Long value) {
            addCriterion("gps_ts >=", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsLessThan(Long value) {
            addCriterion("gps_ts <", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsLessThanOrEqualTo(Long value) {
            addCriterion("gps_ts <=", value, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsIn(List<Long> values) {
            addCriterion("gps_ts in", values, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsNotIn(List<Long> values) {
            addCriterion("gps_ts not in", values, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsBetween(Long value1, Long value2) {
            addCriterion("gps_ts between", value1, value2, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andGpsTsNotBetween(Long value1, Long value2) {
            addCriterion("gps_ts not between", value1, value2, "gpsTs");
            return (Criteria) this;
        }

        public Criteria andDevMcIsNull() {
            addCriterion("dev_mc is null");
            return (Criteria) this;
        }

        public Criteria andDevMcIsNotNull() {
            addCriterion("dev_mc is not null");
            return (Criteria) this;
        }

        public Criteria andDevMcEqualTo(String value) {
            addCriterion("dev_mc =", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcNotEqualTo(String value) {
            addCriterion("dev_mc <>", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcGreaterThan(String value) {
            addCriterion("dev_mc >", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcGreaterThanOrEqualTo(String value) {
            addCriterion("dev_mc >=", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcLessThan(String value) {
            addCriterion("dev_mc <", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcLessThanOrEqualTo(String value) {
            addCriterion("dev_mc <=", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcLike(String value) {
            addCriterion("dev_mc like", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcNotLike(String value) {
            addCriterion("dev_mc not like", value, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcIn(List<String> values) {
            addCriterion("dev_mc in", values, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcNotIn(List<String> values) {
            addCriterion("dev_mc not in", values, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcBetween(String value1, String value2) {
            addCriterion("dev_mc between", value1, value2, "devMc");
            return (Criteria) this;
        }

        public Criteria andDevMcNotBetween(String value1, String value2) {
            addCriterion("dev_mc not between", value1, value2, "devMc");
            return (Criteria) this;
        }

        public Criteria andBatVolIsNull() {
            addCriterion("bat_vol is null");
            return (Criteria) this;
        }

        public Criteria andBatVolIsNotNull() {
            addCriterion("bat_vol is not null");
            return (Criteria) this;
        }

        public Criteria andBatVolEqualTo(Integer value) {
            addCriterion("bat_vol =", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolNotEqualTo(Integer value) {
            addCriterion("bat_vol <>", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolGreaterThan(Integer value) {
            addCriterion("bat_vol >", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolGreaterThanOrEqualTo(Integer value) {
            addCriterion("bat_vol >=", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolLessThan(Integer value) {
            addCriterion("bat_vol <", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolLessThanOrEqualTo(Integer value) {
            addCriterion("bat_vol <=", value, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolIn(List<Integer> values) {
            addCriterion("bat_vol in", values, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolNotIn(List<Integer> values) {
            addCriterion("bat_vol not in", values, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolBetween(Integer value1, Integer value2) {
            addCriterion("bat_vol between", value1, value2, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatVolNotBetween(Integer value1, Integer value2) {
            addCriterion("bat_vol not between", value1, value2, "batVol");
            return (Criteria) this;
        }

        public Criteria andBatCapIsNull() {
            addCriterion("bat_cap is null");
            return (Criteria) this;
        }

        public Criteria andBatCapIsNotNull() {
            addCriterion("bat_cap is not null");
            return (Criteria) this;
        }

        public Criteria andBatCapEqualTo(Integer value) {
            addCriterion("bat_cap =", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapNotEqualTo(Integer value) {
            addCriterion("bat_cap <>", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapGreaterThan(Integer value) {
            addCriterion("bat_cap >", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapGreaterThanOrEqualTo(Integer value) {
            addCriterion("bat_cap >=", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapLessThan(Integer value) {
            addCriterion("bat_cap <", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapLessThanOrEqualTo(Integer value) {
            addCriterion("bat_cap <=", value, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapIn(List<Integer> values) {
            addCriterion("bat_cap in", values, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapNotIn(List<Integer> values) {
            addCriterion("bat_cap not in", values, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapBetween(Integer value1, Integer value2) {
            addCriterion("bat_cap between", value1, value2, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatCapNotBetween(Integer value1, Integer value2) {
            addCriterion("bat_cap not between", value1, value2, "batCap");
            return (Criteria) this;
        }

        public Criteria andBatSnIsNull() {
            addCriterion("bat_sn is null");
            return (Criteria) this;
        }

        public Criteria andBatSnIsNotNull() {
            addCriterion("bat_sn is not null");
            return (Criteria) this;
        }

        public Criteria andBatSnEqualTo(String value) {
            addCriterion("bat_sn =", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnNotEqualTo(String value) {
            addCriterion("bat_sn <>", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnGreaterThan(String value) {
            addCriterion("bat_sn >", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnGreaterThanOrEqualTo(String value) {
            addCriterion("bat_sn >=", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnLessThan(String value) {
            addCriterion("bat_sn <", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnLessThanOrEqualTo(String value) {
            addCriterion("bat_sn <=", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnLike(String value) {
            addCriterion("bat_sn like", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnNotLike(String value) {
            addCriterion("bat_sn not like", value, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnIn(List<String> values) {
            addCriterion("bat_sn in", values, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnNotIn(List<String> values) {
            addCriterion("bat_sn not in", values, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnBetween(String value1, String value2) {
            addCriterion("bat_sn between", value1, value2, "batSn");
            return (Criteria) this;
        }

        public Criteria andBatSnNotBetween(String value1, String value2) {
            addCriterion("bat_sn not between", value1, value2, "batSn");
            return (Criteria) this;
        }

        public Criteria andDevStatusIsNull() {
            addCriterion("dev_status is null");
            return (Criteria) this;
        }

        public Criteria andDevStatusIsNotNull() {
            addCriterion("dev_status is not null");
            return (Criteria) this;
        }

        public Criteria andDevStatusEqualTo(Integer value) {
            addCriterion("dev_status =", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusNotEqualTo(Integer value) {
            addCriterion("dev_status <>", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusGreaterThan(Integer value) {
            addCriterion("dev_status >", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("dev_status >=", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusLessThan(Integer value) {
            addCriterion("dev_status <", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusLessThanOrEqualTo(Integer value) {
            addCriterion("dev_status <=", value, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusIn(List<Integer> values) {
            addCriterion("dev_status in", values, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusNotIn(List<Integer> values) {
            addCriterion("dev_status not in", values, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusBetween(Integer value1, Integer value2) {
            addCriterion("dev_status between", value1, value2, "devStatus");
            return (Criteria) this;
        }

        public Criteria andDevStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("dev_status not between", value1, value2, "devStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gps
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gps
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}