package com.gps.manager.entity;

import java.io.Serializable;

public class GpsFirm implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4888946782782280532L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_firm.firm_id
     *
     * @mbggenerated
     */
    private Integer firmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_firm.firm_name
     *
     * @mbggenerated
     */
    private String firmName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_firm.firm_id
     *
     * @return the value of gps_firm.firm_id
     *
     * @mbggenerated
     */
    public Integer getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_firm.firm_id
     *
     * @param firmId the value for gps_firm.firm_id
     *
     * @mbggenerated
     */
    public void setFirmId(Integer firmId) {
        this.firmId = firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_firm.firm_name
     *
     * @return the value of gps_firm.firm_name
     *
     * @mbggenerated
     */
    public String getFirmName() {
        return firmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_firm.firm_name
     *
     * @param firmName the value for gps_firm.firm_name
     *
     * @mbggenerated
     */
    public void setFirmName(String firmName) {
        this.firmName = firmName == null ? null : firmName.trim();
    }
}