package com.gps.manager.entity;

import java.io.Serializable;

public class GpsMode implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5111083442298690543L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_mode.mode_id
     *
     * @mbggenerated
     */
    private Integer modeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_mode.mode_name
     *
     * @mbggenerated
     */
    private String modeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_mode.mode_id
     *
     * @return the value of gps_mode.mode_id
     *
     * @mbggenerated
     */
    public Integer getModeId() {
        return modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_mode.mode_id
     *
     * @param modeId the value for gps_mode.mode_id
     *
     * @mbggenerated
     */
    public void setModeId(Integer modeId) {
        this.modeId = modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_mode.mode_name
     *
     * @return the value of gps_mode.mode_name
     *
     * @mbggenerated
     */
    public String getModeName() {
        return modeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_mode.mode_name
     *
     * @param modeName the value for gps_mode.mode_name
     *
     * @mbggenerated
     */
    public void setModeName(String modeName) {
        this.modeName = modeName == null ? null : modeName.trim();
    }
}