package com.gps.manager.entity;

import java.io.Serializable;

public class GpsType implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 742335640391446288L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_type.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_type.type_id
     *
     * @return the value of gps_type.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_type.type_id
     *
     * @param typeId the value for gps_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_type.type_name
     *
     * @return the value of gps_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_type.type_name
     *
     * @param typeName the value for gps_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}