package com.gps.manager.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public ProjExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProjIdIsNull() {
            addCriterion("proj_id is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("proj_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Integer value) {
            addCriterion("proj_id <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Integer value) {
            addCriterion("proj_id >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("proj_id >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Integer value) {
            addCriterion("proj_id <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Integer value) {
            addCriterion("proj_id <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Integer> values) {
            addCriterion("proj_id in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Integer> values) {
            addCriterion("proj_id not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Integer value1, Integer value2) {
            addCriterion("proj_id between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("proj_id not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjNameIsNull() {
            addCriterion("proj_name is null");
            return (Criteria) this;
        }

        public Criteria andProjNameIsNotNull() {
            addCriterion("proj_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjNameEqualTo(String value) {
            addCriterion("proj_name =", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameNotEqualTo(String value) {
            addCriterion("proj_name <>", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameGreaterThan(String value) {
            addCriterion("proj_name >", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameGreaterThanOrEqualTo(String value) {
            addCriterion("proj_name >=", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameLessThan(String value) {
            addCriterion("proj_name <", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameLessThanOrEqualTo(String value) {
            addCriterion("proj_name <=", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameLike(String value) {
            addCriterion("proj_name like", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameNotLike(String value) {
            addCriterion("proj_name not like", value, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameIn(List<String> values) {
            addCriterion("proj_name in", values, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameNotIn(List<String> values) {
            addCriterion("proj_name not in", values, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameBetween(String value1, String value2) {
            addCriterion("proj_name between", value1, value2, "projName");
            return (Criteria) this;
        }

        public Criteria andProjNameNotBetween(String value1, String value2) {
            addCriterion("proj_name not between", value1, value2, "projName");
            return (Criteria) this;
        }

        public Criteria andProjIpIsNull() {
            addCriterion("proj_ip is null");
            return (Criteria) this;
        }

        public Criteria andProjIpIsNotNull() {
            addCriterion("proj_ip is not null");
            return (Criteria) this;
        }

        public Criteria andProjIpEqualTo(String value) {
            addCriterion("proj_ip =", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpNotEqualTo(String value) {
            addCriterion("proj_ip <>", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpGreaterThan(String value) {
            addCriterion("proj_ip >", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpGreaterThanOrEqualTo(String value) {
            addCriterion("proj_ip >=", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpLessThan(String value) {
            addCriterion("proj_ip <", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpLessThanOrEqualTo(String value) {
            addCriterion("proj_ip <=", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpLike(String value) {
            addCriterion("proj_ip like", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpNotLike(String value) {
            addCriterion("proj_ip not like", value, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpIn(List<String> values) {
            addCriterion("proj_ip in", values, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpNotIn(List<String> values) {
            addCriterion("proj_ip not in", values, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpBetween(String value1, String value2) {
            addCriterion("proj_ip between", value1, value2, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjIpNotBetween(String value1, String value2) {
            addCriterion("proj_ip not between", value1, value2, "projIp");
            return (Criteria) this;
        }

        public Criteria andProjKeyIsNull() {
            addCriterion("proj_key is null");
            return (Criteria) this;
        }

        public Criteria andProjKeyIsNotNull() {
            addCriterion("proj_key is not null");
            return (Criteria) this;
        }

        public Criteria andProjKeyEqualTo(String value) {
            addCriterion("proj_key =", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyNotEqualTo(String value) {
            addCriterion("proj_key <>", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyGreaterThan(String value) {
            addCriterion("proj_key >", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyGreaterThanOrEqualTo(String value) {
            addCriterion("proj_key >=", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyLessThan(String value) {
            addCriterion("proj_key <", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyLessThanOrEqualTo(String value) {
            addCriterion("proj_key <=", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyLike(String value) {
            addCriterion("proj_key like", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyNotLike(String value) {
            addCriterion("proj_key not like", value, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyIn(List<String> values) {
            addCriterion("proj_key in", values, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyNotIn(List<String> values) {
            addCriterion("proj_key not in", values, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyBetween(String value1, String value2) {
            addCriterion("proj_key between", value1, value2, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjKeyNotBetween(String value1, String value2) {
            addCriterion("proj_key not between", value1, value2, "projKey");
            return (Criteria) this;
        }

        public Criteria andProjBeginIsNull() {
            addCriterion("proj_begin is null");
            return (Criteria) this;
        }

        public Criteria andProjBeginIsNotNull() {
            addCriterion("proj_begin is not null");
            return (Criteria) this;
        }

        public Criteria andProjBeginEqualTo(Date value) {
            addCriterionForJDBCDate("proj_begin =", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginNotEqualTo(Date value) {
            addCriterionForJDBCDate("proj_begin <>", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginGreaterThan(Date value) {
            addCriterionForJDBCDate("proj_begin >", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("proj_begin >=", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginLessThan(Date value) {
            addCriterionForJDBCDate("proj_begin <", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("proj_begin <=", value, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginIn(List<Date> values) {
            addCriterionForJDBCDate("proj_begin in", values, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginNotIn(List<Date> values) {
            addCriterionForJDBCDate("proj_begin not in", values, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("proj_begin between", value1, value2, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjBeginNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("proj_begin not between", value1, value2, "projBegin");
            return (Criteria) this;
        }

        public Criteria andProjEndIsNull() {
            addCriterion("proj_end is null");
            return (Criteria) this;
        }

        public Criteria andProjEndIsNotNull() {
            addCriterion("proj_end is not null");
            return (Criteria) this;
        }

        public Criteria andProjEndEqualTo(Date value) {
            addCriterionForJDBCDate("proj_end =", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("proj_end <>", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndGreaterThan(Date value) {
            addCriterionForJDBCDate("proj_end >", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("proj_end >=", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndLessThan(Date value) {
            addCriterionForJDBCDate("proj_end <", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("proj_end <=", value, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndIn(List<Date> values) {
            addCriterionForJDBCDate("proj_end in", values, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("proj_end not in", values, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("proj_end between", value1, value2, "projEnd");
            return (Criteria) this;
        }

        public Criteria andProjEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("proj_end not between", value1, value2, "projEnd");
            return (Criteria) this;
        }

        public Criteria andContNameIsNull() {
            addCriterion("cont_name is null");
            return (Criteria) this;
        }

        public Criteria andContNameIsNotNull() {
            addCriterion("cont_name is not null");
            return (Criteria) this;
        }

        public Criteria andContNameEqualTo(String value) {
            addCriterion("cont_name =", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameNotEqualTo(String value) {
            addCriterion("cont_name <>", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameGreaterThan(String value) {
            addCriterion("cont_name >", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameGreaterThanOrEqualTo(String value) {
            addCriterion("cont_name >=", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameLessThan(String value) {
            addCriterion("cont_name <", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameLessThanOrEqualTo(String value) {
            addCriterion("cont_name <=", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameLike(String value) {
            addCriterion("cont_name like", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameNotLike(String value) {
            addCriterion("cont_name not like", value, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameIn(List<String> values) {
            addCriterion("cont_name in", values, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameNotIn(List<String> values) {
            addCriterion("cont_name not in", values, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameBetween(String value1, String value2) {
            addCriterion("cont_name between", value1, value2, "contName");
            return (Criteria) this;
        }

        public Criteria andContNameNotBetween(String value1, String value2) {
            addCriterion("cont_name not between", value1, value2, "contName");
            return (Criteria) this;
        }

        public Criteria andContPhoneIsNull() {
            addCriterion("cont_phone is null");
            return (Criteria) this;
        }

        public Criteria andContPhoneIsNotNull() {
            addCriterion("cont_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContPhoneEqualTo(String value) {
            addCriterion("cont_phone =", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneNotEqualTo(String value) {
            addCriterion("cont_phone <>", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneGreaterThan(String value) {
            addCriterion("cont_phone >", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("cont_phone >=", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneLessThan(String value) {
            addCriterion("cont_phone <", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneLessThanOrEqualTo(String value) {
            addCriterion("cont_phone <=", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneLike(String value) {
            addCriterion("cont_phone like", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneNotLike(String value) {
            addCriterion("cont_phone not like", value, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneIn(List<String> values) {
            addCriterion("cont_phone in", values, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneNotIn(List<String> values) {
            addCriterion("cont_phone not in", values, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneBetween(String value1, String value2) {
            addCriterion("cont_phone between", value1, value2, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContPhoneNotBetween(String value1, String value2) {
            addCriterion("cont_phone not between", value1, value2, "contPhone");
            return (Criteria) this;
        }

        public Criteria andContEmailIsNull() {
            addCriterion("cont_email is null");
            return (Criteria) this;
        }

        public Criteria andContEmailIsNotNull() {
            addCriterion("cont_email is not null");
            return (Criteria) this;
        }

        public Criteria andContEmailEqualTo(String value) {
            addCriterion("cont_email =", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailNotEqualTo(String value) {
            addCriterion("cont_email <>", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailGreaterThan(String value) {
            addCriterion("cont_email >", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailGreaterThanOrEqualTo(String value) {
            addCriterion("cont_email >=", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailLessThan(String value) {
            addCriterion("cont_email <", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailLessThanOrEqualTo(String value) {
            addCriterion("cont_email <=", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailLike(String value) {
            addCriterion("cont_email like", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailNotLike(String value) {
            addCriterion("cont_email not like", value, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailIn(List<String> values) {
            addCriterion("cont_email in", values, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailNotIn(List<String> values) {
            addCriterion("cont_email not in", values, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailBetween(String value1, String value2) {
            addCriterion("cont_email between", value1, value2, "contEmail");
            return (Criteria) this;
        }

        public Criteria andContEmailNotBetween(String value1, String value2) {
            addCriterion("cont_email not between", value1, value2, "contEmail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}