package com.gps.manager.entity;

import java.io.Serializable;
import java.util.Date;

public class Proj implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2445506133671316924L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_id
     *
     * @mbggenerated
     */
    private Integer projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_name
     *
     * @mbggenerated
     */
    private String projName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_ip
     *
     * @mbggenerated
     */
    private String projIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_key
     *
     * @mbggenerated
     */
    private String projKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_begin
     *
     * @mbggenerated
     */
    private Date projBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.proj_end
     *
     * @mbggenerated
     */
    private Date projEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.cont_name
     *
     * @mbggenerated
     */
    private String contName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.cont_phone
     *
     * @mbggenerated
     */
    private String contPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj.cont_email
     *
     * @mbggenerated
     */
    private String contEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_id
     *
     * @return the value of proj.proj_id
     *
     * @mbggenerated
     */
    public Integer getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_id
     *
     * @param projId the value for proj.proj_id
     *
     * @mbggenerated
     */
    public void setProjId(Integer projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_name
     *
     * @return the value of proj.proj_name
     *
     * @mbggenerated
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_name
     *
     * @param projName the value for proj.proj_name
     *
     * @mbggenerated
     */
    public void setProjName(String projName) {
        this.projName = projName == null ? null : projName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_ip
     *
     * @return the value of proj.proj_ip
     *
     * @mbggenerated
     */
    public String getProjIp() {
        return projIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_ip
     *
     * @param projIp the value for proj.proj_ip
     *
     * @mbggenerated
     */
    public void setProjIp(String projIp) {
        this.projIp = projIp == null ? null : projIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_key
     *
     * @return the value of proj.proj_key
     *
     * @mbggenerated
     */
    public String getProjKey() {
        return projKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_key
     *
     * @param projKey the value for proj.proj_key
     *
     * @mbggenerated
     */
    public void setProjKey(String projKey) {
        this.projKey = projKey == null ? null : projKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_begin
     *
     * @return the value of proj.proj_begin
     *
     * @mbggenerated
     */
    public Date getProjBegin() {
        return projBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_begin
     *
     * @param projBegin the value for proj.proj_begin
     *
     * @mbggenerated
     */
    public void setProjBegin(Date projBegin) {
        this.projBegin = projBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.proj_end
     *
     * @return the value of proj.proj_end
     *
     * @mbggenerated
     */
    public Date getProjEnd() {
        return projEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.proj_end
     *
     * @param projEnd the value for proj.proj_end
     *
     * @mbggenerated
     */
    public void setProjEnd(Date projEnd) {
        this.projEnd = projEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.cont_name
     *
     * @return the value of proj.cont_name
     *
     * @mbggenerated
     */
    public String getContName() {
        return contName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.cont_name
     *
     * @param contName the value for proj.cont_name
     *
     * @mbggenerated
     */
    public void setContName(String contName) {
        this.contName = contName == null ? null : contName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.cont_phone
     *
     * @return the value of proj.cont_phone
     *
     * @mbggenerated
     */
    public String getContPhone() {
        return contPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.cont_phone
     *
     * @param contPhone the value for proj.cont_phone
     *
     * @mbggenerated
     */
    public void setContPhone(String contPhone) {
        this.contPhone = contPhone == null ? null : contPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj.cont_email
     *
     * @return the value of proj.cont_email
     *
     * @mbggenerated
     */
    public String getContEmail() {
        return contEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj.cont_email
     *
     * @param contEmail the value for proj.cont_email
     *
     * @mbggenerated
     */
    public void setContEmail(String contEmail) {
        this.contEmail = contEmail == null ? null : contEmail.trim();
    }
}