package com.gps.manager.dao;

import com.gps.manager.entity.Attach;
import com.gps.manager.entity.AttachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int countByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int deleteByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int insert(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int insertSelective(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    List<Attach> selectByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    Attach selectByPrimaryKey(Integer attachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attach
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attach record);
}