package com.gps.manager.dao;

import com.gps.manager.entity.GpsFirm;
import com.gps.manager.entity.GpsFirmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpsFirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int countByExample(GpsFirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int deleteByExample(GpsFirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer firmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int insert(GpsFirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int insertSelective(GpsFirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    List<GpsFirm> selectByExample(GpsFirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    GpsFirm selectByPrimaryKey(Integer firmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GpsFirm record, @Param("example") GpsFirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GpsFirm record, @Param("example") GpsFirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GpsFirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_firm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GpsFirm record);
}