package com.gps.manager.dao;

import com.gps.manager.entity.Gps;
import com.gps.manager.entity.GpsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int countByExample(GpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int deleteByExample(GpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int insert(Gps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int insertSelective(Gps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    List<Gps> selectByExample(GpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    Gps selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Gps record, @Param("example") GpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Gps record, @Param("example") GpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Gps record);
}