package com.gps.manager.dao;

import com.gps.manager.entity.GpsMode;
import com.gps.manager.entity.GpsModeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpsModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int countByExample(GpsModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int deleteByExample(GpsModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer modeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int insert(GpsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int insertSelective(GpsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    List<GpsMode> selectByExample(GpsModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    GpsMode selectByPrimaryKey(Integer modeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GpsMode record, @Param("example") GpsModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GpsMode record, @Param("example") GpsModeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GpsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_mode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GpsMode record);
}