package com.gps.manager.dao;

import com.gps.manager.entity.Proj;
import com.gps.manager.entity.ProjExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int countByExample(ProjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int deleteByExample(ProjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer projId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int insert(Proj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int insertSelective(Proj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    List<Proj> selectByExample(ProjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    Proj selectByPrimaryKey(Integer projId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Proj record, @Param("example") ProjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Proj record, @Param("example") ProjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Proj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Proj record);
}